using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.Xml;
using System.Xml.Serialization;
using NetMX.Remote.Jsr262.Structures;
using WSMan.NET;

namespace NetMX.Remote.Jsr262
{
   //------------------------------------------------------------------------------
   // <auto-generated>
   //     This code was generated by a tool.
   //     Runtime Version:2.0.50727.1433
   //
   //     Changes to this file may cause incorrect behavior and will be lost if
   //     the code is regenerated.
   // </auto-generated>
   //------------------------------------------------------------------------------

   // 
   // This source code was auto-generated by xsd, Version=2.0.50727.1432.
   //     


   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class TwoQueries
   {
      private QueryExpr[] queryField;


      [XmlElement("Query")]
      public QueryExpr[] Query
      {
         get { return queryField; }
         set { queryField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Query", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class QueryExpr
   {
      private ItemChoiceType1 itemElementNameField;
      private object itemField;


      [XmlElement("And", typeof(TwoQueries))]
      [XmlElement("Between", typeof(QueryExprBetween))]
      [XmlElement("In", typeof(QueryExprIN))]
      [XmlElement("InstanceOf", typeof(ValueExpr))]
      [XmlElement("Match", typeof(TwoValues))]
      [XmlElement("MatchName", typeof(string))]
      [XmlElement("Not", typeof(QueryExprNot))]
      [XmlElement("Or", typeof(TwoQueries))]
      [XmlElement("Rel", typeof(QueryExprRel))]
      [XmlChoiceIdentifier("ItemElementName")]
      public object Item
      {
         get { return itemField; }
         set { itemField = value; }
      }


      [XmlIgnore]
      public ItemChoiceType1 ItemElementName
      {
         get { return itemElementNameField; }
         set { itemElementNameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class QueryExprBetween
   {
      private ValueExpr[] valueField;


      [XmlElement("Value")]
      public ValueExpr[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Value", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ValueExpr
   {
      private object itemField;


      [XmlElement("Attr", typeof(ValueExprAttr))]
      [XmlElement("Boolean", typeof(bool))]
      [XmlElement("Class", typeof(ValueExprClass))]
      [XmlElement("Double", typeof(double))]
      [XmlElement("Long", typeof(long))]
      [XmlElement("Op", typeof(ValueExprOP))]
      [XmlElement("String", typeof(string))]
      public object Item
      {
         get { return itemField; }
         set { itemField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class ValueExprAttr
   {
      private string classField;
      private string nameField;


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }


      [XmlAttribute]
      public string @class
      {
         get { return classField; }
         set { classField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class ValueExprClass
   {
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class ValueExprOP
   {
      private BinOp opField;
      private ValueExpr[] valueField;


      [XmlElement("Value")]
      public ValueExpr[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }


      [XmlAttribute]
      public BinOp op
      {
         get { return opField; }
         set { opField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public enum BinOp
   {
      [XmlEnum("+")]
      Item,


      [XmlEnum("-")]
      Item1,


      [XmlEnum("*")]
      Item2,


      [XmlEnum("/")]
      Item3,
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class QueryExprIN
   {
      private ValueExpr[] valueField;


      [XmlElement("Value")]
      public ValueExpr[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class TwoValues
   {
      private ValueExpr[] valueField;


      [XmlElement("Value")]
      public ValueExpr[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class QueryExprNot
   {
      private QueryExpr queryField;


      public QueryExpr Query
      {
         get { return queryField; }
         set { queryField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class QueryExprRel
   {
      private RelOp opField;
      private ValueExpr[] valueField;


      [XmlElement("Value")]
      public ValueExpr[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }


      [XmlAttribute]
      public RelOp op
      {
         get { return opField; }
         set { opField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public enum RelOp
   {
      [XmlEnum("=")]
      Item,


      [XmlEnum("!=")]
      Item1,


      [XmlEnum("<")]
      Item2,


      [XmlEnum(">")]
      Item3,


      [XmlEnum("<=")]
      Item4,


      [XmlEnum(">=")]
      Item5,
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector", IncludeInSchema = false)]
   public enum ItemChoiceType1
   {
      And,


      Between,


      In,


      InstanceOf,


      Match,


      MatchName,


      Not,


      Or,


      Rel,
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class OperationResultType
   {
      private GenericValueType resultField;


      public GenericValueType Result
      {
         get { return resultField; }
         set { resultField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class Enumeration
   {
      private string typeField;

      private string valueField;


      [XmlAttribute]
      public string type
      {
         get { return typeField; }
         set { typeField = value; }
      }


      [XmlAttribute]
      public string value
      {
         get { return valueField; }
         set { valueField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Fault", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagementFaultType
   {
      private ManagementFaultType faultCauseField;

      private string faultClassField;
      private string faultMessageField;
      private StackTraceElementType[] stackTraceElementField;


      public string FaultMessage
      {
         get { return faultMessageField; }
         set { faultMessageField = value; }
      }


      public ManagementFaultType FaultCause
      {
         get { return faultCauseField; }
         set { faultCauseField = value; }
      }


      [XmlElement("StackTraceElement")]
      public StackTraceElementType[] StackTraceElement
      {
         get { return stackTraceElementField; }
         set { stackTraceElementField = value; }
      }


      [XmlAttribute]
      public string faultClass
      {
         get { return faultClassField; }
         set { faultClassField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class StackTraceElementType
   {
      private string declaringClassField;

      private string fileNameField;

      private int lineNumberField;

      private bool lineNumberFieldSpecified;
      private string methodNameField;


      [XmlAttribute]
      public string DeclaringClass
      {
         get { return declaringClassField; }
         set { declaringClassField = value; }
      }


      [XmlAttribute]
      public string MethodName
      {
         get { return methodNameField; }
         set { methodNameField = value; }
      }


      [XmlAttribute]
      public string FileName
      {
         get { return fileNameField; }
         set { fileNameField = value; }
      }


      [XmlAttribute]
      public int LineNumber
      {
         get { return lineNumberField; }
         set { lineNumberField = value; }
      }


      [XmlIgnore]
      public bool LineNumberSpecified
      {
         get { return lineNumberFieldSpecified; }
         set { lineNumberFieldSpecified = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Values", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class MultipleValueType
   {
      private GenericValueType[] valueField;


      [XmlElement("Value")]
      public GenericValueType[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceRelationType
   {
      private ManagedResourceRoleInfo[] managedResourceRoleInfoField;

      private string nameField;


      [XmlElement("ManagedResourceRoleInfo")]
      public ManagedResourceRoleInfo[] ManagedResourceRoleInfo
      {
         get { return managedResourceRoleInfoField; }
         set { managedResourceRoleInfoField = value; }
      }


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceRoleInfo
   {
      private string accessField;
      private string descriptionField;
      private string managedResourceClassNameField;

      private int maxDegreeField;

      private bool maxDegreeFieldSpecified;
      private int minDegreeField;

      private bool minDegreeFieldSpecified;
      private string nameField;


      public string ManagedResourceClassName
      {
         get { return managedResourceClassNameField; }
         set { managedResourceClassNameField = value; }
      }


      public string Description
      {
         get { return descriptionField; }
         set { descriptionField = value; }
      }


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }


      [XmlAttribute]
      public string access
      {
         get { return accessField; }
         set { accessField = value; }
      }


      [XmlAttribute]
      public int minDegree
      {
         get { return minDegreeField; }
         set { minDegreeField = value; }
      }


      [XmlIgnore]
      public bool minDegreeSpecified
      {
         get { return minDegreeFieldSpecified; }
         set { minDegreeFieldSpecified = value; }
      }


      [XmlAttribute]
      public int maxDegree
      {
         get { return maxDegreeField; }
         set { maxDegreeField = value; }
      }


      [XmlIgnore]
      public bool maxDegreeSpecified
      {
         get { return maxDegreeFieldSpecified; }
         set { maxDegreeFieldSpecified = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceRole
   {
      private string nameField;
      private EndpointReference[] valueField;


      [XmlElement("Value")]
      public EndpointReference[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceRoleList
   {
      private ManagedResourceRole[] managedResourceRoleField;


      [XmlElement("ManagedResourceRole")]
      public ManagedResourceRole[] ManagedResourceRole
      {
         get { return managedResourceRoleField; }
         set { managedResourceRoleField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceRoleResult
   {
      private ManagedResourceRoleList managedResourceRoleListField;
      private ManagedResourceRoleUnresolvedList managedResourceRoleUnresolvedListField;


      [XmlElement("ManagedResourceRoleList", typeof(ManagedResourceRoleList))]
      public ManagedResourceRoleList ManagedResourceRoleList
      {
         get { return managedResourceRoleListField; }
         set { managedResourceRoleListField = value; }
      }


      [XmlElement("ManagedResourceRoleUnresolvedList", typeof(ManagedResourceRoleUnresolvedList))]
      public ManagedResourceRoleUnresolvedList ManagedResourceRoleUnresolvedList
      {
         get { return managedResourceRoleUnresolvedListField; }
         set { managedResourceRoleUnresolvedListField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceRoleUnresolvedList
   {
      private ManagedResourceRoleUnresolved[] managedResourceRoleUnresolvedField;


      [XmlElement("ManagedResourceRoleUnresolved")]
      public ManagedResourceRoleUnresolved[] ManagedResourceRoleUnresolved
      {
         get { return managedResourceRoleUnresolvedField; }
         set { managedResourceRoleUnresolvedField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceRoleUnresolved
   {
      private string nameField;

      private int problemField;

      private bool problemFieldSpecified;
      private EndpointReference[] valueField;


      [XmlElement("Value")]
      public EndpointReference[] Value
      {
         get { return valueField; }
         set { valueField = value; }
      }


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }


      [XmlAttribute]
      public int problem
      {
         get { return problemField; }
         set { problemField = value; }
      }


      [XmlIgnore]
      public bool problemSpecified
      {
         get { return problemFieldSpecified; }
         set { problemFieldSpecified = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Map", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class MapType
   {
      private MapTypeEntry[] entryField;


      [XmlElement("Entry")]
      public MapTypeEntry[] Entry
      {
         get { return entryField; }
         set { entryField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class MapTypeEntry
   {
      private GenericValueType keyField;

      private GenericValueType valueField;


      public GenericValueType Key
      {
         get { return keyField; }
         set { keyField = value; }
      }


      public GenericValueType Value
      {
         get { return valueField; }
         set { valueField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NotificationResult
   {
      private long earliestSequenceNumberField;

      private bool earliestSequenceNumberFieldSpecified;

      private long nextSequenceNumberField;

      private bool nextSequenceNumberFieldSpecified;
      private TargetedNotificationType[] targetedNotificationField;


      [XmlElement("TargetedNotification")]
      public TargetedNotificationType[] TargetedNotification
      {
         get { return targetedNotificationField; }
         set { targetedNotificationField = value; }
      }


      [XmlAttribute]
      public long earliestSequenceNumber
      {
         get { return earliestSequenceNumberField; }
         set { earliestSequenceNumberField = value; }
      }


      [XmlIgnore]
      public bool earliestSequenceNumberSpecified
      {
         get { return earliestSequenceNumberFieldSpecified; }
         set { earliestSequenceNumberFieldSpecified = value; }
      }


      [XmlAttribute]
      public long nextSequenceNumber
      {
         get { return nextSequenceNumberField; }
         set { nextSequenceNumberField = value; }
      }


      [XmlIgnore]
      public bool nextSequenceNumberSpecified
      {
         get { return nextSequenceNumberFieldSpecified; }
         set { nextSequenceNumberFieldSpecified = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Null", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NullType
   {
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Table", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class TableType
   {
      private int dimensionField;

      private bool dimensionFieldSpecified;
      private XmlQualifiedName leafTypeField;
      private bool primitiveField;

      private bool primitiveFieldSpecified;
      private GenericValueType[] valuesField;


      [XmlArrayItem("Value", IsNullable = false)]
      public GenericValueType[] Values
      {
         get { return valuesField; }
         set { valuesField = value; }
      }


      [XmlAttribute]
      public bool primitive
      {
         get { return primitiveField; }
         set { primitiveField = value; }
      }


      [XmlIgnore]
      public bool primitiveSpecified
      {
         get { return primitiveFieldSpecified; }
         set { primitiveFieldSpecified = value; }
      }


      [XmlAttribute]
      public XmlQualifiedName leafType
      {
         get { return leafTypeField; }
         set { leafTypeField = value; }
      }


      [XmlAttribute]
      public int dimension
      {
         get { return dimensionField; }
         set { dimensionField = value; }
      }


      [XmlIgnore]
      public bool dimensionSpecified
      {
         get { return dimensionFieldSpecified; }
         set { dimensionFieldSpecified = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector", IncludeInSchema = false)]
   public enum ItemChoiceType
   {
      ArrayDataType,


      Base64Binary,


      Boolean,


      Byte,


      Character,


      CompositeDataType,


      CompositeDataValue,


      Custom,


      Date,


      DateTime,


      Decimal,


      Double,


      Duration,


      EndpointReference,


      Enumeration,


      Fault,


      Float,


      Int,


      Integer,


      List,


      TypedList,


      Long,


      ManagedResourceRelationType,


      ManagedResourceRole,


      ManagedResourceRoleInfo,


      ManagedResourceRoleList,


      ManagedResourceRoleResult,


      ManagedResourceRoleUnresolved,


      ManagedResourceRoleUnresolvedList,


      Map,

      TypedMap,


      NotificationFilter,


      NotificationResult,


      Null,


      QName,


      ServiceURL,


      Set,


      Short,


      SimpleDataType,


      String,


      Table,


      TabularDataType,


      TabularDataValue,


      URI,


      URL,


      UUID,


      Vector,
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class Description
   {
      private string langField;

      private string valueField;


      [XmlAttribute(DataType = "language")]
      public string lang
      {
         get { return langField; }
         set { langField = value; }
      }


      [XmlText]
      public string Value
      {
         get { return valueField; }
         set { valueField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   public partial class PropertyType : TypedFeatureInfoType
   {
   }
   
   /// <remarks/>
   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]
   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class DynamicMBeanResource
   {
      private NamedGenericValueType[] propertyField;

      /// <remarks/>
      [XmlElement("Property")]
      [MessageBodyMember(Name = "GetResult")]
      public NamedGenericValueType[] Property
      {
         get { return propertyField; }
         set { propertyField = value; }
      }
   }   

   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Property", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NamedGenericValueType : GenericValueType
   {
      private string nameField;


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class DynamicMBeanResourceConstructor
   {
      private object itemField;

      private ParameterType[] registrationParametersField;

      private ParameterSignatureType[] registrationSignatureField;
      private string resourceClassField;
      private EndpointReference resourceEPRField;


      public EndpointReference ResourceEPR
      {
         get { return resourceEPRField; }
         set { resourceEPRField = value; }
      }


      public string ResourceClass
      {
         get { return resourceClassField; }
         set { resourceClassField = value; }
      }


      [XmlElement("ResourceLoaderEPR", typeof(EndpointReference))]
      [XmlElement("UseDefaultFactory", typeof(bool))]
      public object Item
      {
         get { return itemField; }
         set { itemField = value; }
      }


      [XmlArrayItem("Param", IsNullable = false)]
      public ParameterType[] RegistrationParameters
      {
         get { return registrationParametersField; }
         set { registrationParametersField = value; }
      }


      [XmlArrayItem("ParameterSignature", IsNullable = false)]
      public ParameterSignatureType[] RegistrationSignature
      {
         get { return registrationSignatureField; }
         set { registrationSignatureField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Param", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ParameterType : GenericValueType
   {
      private string nameField;


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("ParameterSignature", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ParameterSignatureType
   {
      private int dimensionField;

      private bool dimensionFieldSpecified;
      private bool primitiveField;

      private bool primitiveFieldSpecified;

      private XmlQualifiedName typeField;


      [XmlAttribute]
      public bool primitive
      {
         get { return primitiveField; }
         set { primitiveField = value; }
      }


      [XmlIgnore]
      public bool primitiveSpecified
      {
         get { return primitiveFieldSpecified; }
         set { primitiveFieldSpecified = value; }
      }


      [XmlAttribute]
      public XmlQualifiedName type
      {
         get { return typeField; }
         set { typeField = value; }
      }


      [XmlAttribute]
      public int dimension
      {
         get { return dimensionField; }
         set { dimensionField = value; }
      }


      [XmlIgnore]
      public bool dimensionSpecified
      {
         get { return dimensionFieldSpecified; }
         set { dimensionFieldSpecified = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class MBeanServerResource
   {
      private string defaultDomainField;

      private string[] domainField;


      public string DefaultDomain
      {
         get { return defaultDomainField; }
         set { defaultDomainField = value; }
      }


      [XmlElement("Domain")]
      public string[] Domain
      {
         get { return domainField; }
         set { domainField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class PropertyFault
   {
      private ManagementFaultType faultField;

      private string nameField;


      public ManagementFaultType Fault
      {
         get { return faultField; }
         set { faultField = value; }
      }


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NotificationSubscriber
   {
      private GenericValueType handbackField;

      private XmlElement notificationFilterField;
      private EndpointReference subscriberField;


      public GenericValueType Handback
      {
         get { return handbackField; }
         set { handbackField = value; }
      }


      public EndpointReference Subscriber
      {
         get { return subscriberField; }
         set { subscriberField = value; }
      }


      public XmlElement NotificationFilter
      {
         get { return notificationFilterField; }
         set { notificationFilterField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NotificationSubscription
   {
      private NotificationSource[] notificationSourceField;


      [XmlElement("NotificationSource")]
      public NotificationSource[] NotificationSource
      {
         get { return notificationSourceField; }
         set { notificationSourceField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NotificationSource
   {
      private XmlElement notificationFilterField;
      private EndpointReference sourceField;


      public EndpointReference Source
      {
         get { return sourceField; }
         set { sourceField = value; }
      }


      public XmlElement NotificationFilter
      {
         get { return notificationFilterField; }
         set { notificationFilterField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NotificationUnsubscription
   {
      private string notificationListenerListField;
      private EndpointReference sourceField;


      public EndpointReference Source
      {
         get { return sourceField; }
         set { sourceField = value; }
      }


      public string NotificationListenerList
      {
         get { return notificationListenerListField; }
         set { notificationListenerListField = value; }
      }
   }   

   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class PropertyChange
   {
      private GenericValueType newValueField;
      private GenericValueType oldValueField;

      private string propertyNameField;
      private PropertyType typeField;


      public GenericValueType OldValue
      {
         get { return oldValueField; }
         set { oldValueField = value; }
      }


      public GenericValueType NewValue
      {
         get { return newValueField; }
         set { newValueField = value; }
      }


      public PropertyType Type
      {
         get { return typeField; }
         set { typeField = value; }
      }


      [XmlAttribute]
      public string propertyName
      {
         get { return propertyNameField; }
         set { propertyNameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ManagedResourceChange
   {
      private EndpointReference resourceNameField;


      public EndpointReference ResourceName
      {
         get { return resourceNameField; }
         set { resourceNameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class MonitorChange
   {
      private GenericValueType derivedGaugeField;

      private string observedAttributeField;

      private EndpointReference observedManagedResourceField;

      private GenericValueType triggerField;


      public GenericValueType DerivedGauge
      {
         get { return derivedGaugeField; }
         set { derivedGaugeField = value; }
      }


      public string ObservedAttribute
      {
         get { return observedAttributeField; }
         set { observedAttributeField = value; }
      }


      public EndpointReference ObservedManagedResource
      {
         get { return observedManagedResourceField; }
         set { observedManagedResourceField = value; }
      }


      public GenericValueType Trigger
      {
         get { return triggerField; }
         set { triggerField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class NotificationTypeListFilter
   {
      private string[] notificationTypeField;


      [XmlElement("NotificationType")]
      public string[] NotificationType
      {
         get { return notificationTypeField; }
         set { notificationTypeField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ResourceNameAndNotificationTypeListFilter
   {
      private string[] notificationTypeField;

      private EndpointReference[] resourceNameField;


      [XmlElement("NotificationType")]
      public string[] NotificationType
      {
         get { return notificationTypeField; }
         set { notificationTypeField = value; }
      }


      [XmlElement("ResourceName", IsNullable = true)]
      public EndpointReference[] ResourceName
      {
         get { return resourceNameField; }
         set { resourceNameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class PropertyNameListFilter
   {
      private string[] propertyNameField;


      [XmlElement("PropertyName")]
      public string[] PropertyName
      {
         get { return propertyNameField; }
         set { propertyNameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class QueryFilter
   {
      private QueryExpr queryField;


      public QueryExpr Query
      {
         get { return queryField; }
         set { queryField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Input", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ParameterListType
   {
      private ParameterType[] paramField;


      [XmlElement("Param")]
      public ParameterType[] Param
      {
         get { return paramField; }
         set { paramField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("Signature", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class SignatureListType
   {
      private ParameterSignatureType[] parameterSignatureField;


      [XmlElement("ParameterSignature")]
      public ParameterSignatureType[] ParameterSignature
      {
         get { return parameterSignatureField; }
         set { parameterSignatureField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [MessageContract(WrapperNamespace = Schema.ConnectorNamespace)]
   [DesignerCategory("code")]
   [XmlType(Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot("ManagedResourceOperation", Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class OperationRequestType
   {
      private ParameterType[] inputField;

      private string nameField;
      private ParameterSignatureType[] signatureField;


      [XmlArrayItem("Param", IsNullable = false)]
      public ParameterType[] Input
      {
         get { return inputField; }
         set { inputField = value; }
      }


      [XmlArrayItem("ParameterSignature", IsNullable = false)]
      public ParameterSignatureType[] Signature
      {
         get { return signatureField; }
         set { signatureField = value; }
      }


      [XmlAttribute]
      public string name
      {
         get { return nameField; }
         set { nameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class RoleUpdate
   {
      private EndpointReference[] newRoleField;

      private EndpointReference[] oldRoleField;

      private string roleNameField;


      [XmlElement("NewRole")]
      public EndpointReference[] NewRole
      {
         get { return newRoleField; }
         set { newRoleField = value; }
      }


      [XmlElement("OldRole")]
      public EndpointReference[] OldRole
      {
         get { return oldRoleField; }
         set { oldRoleField = value; }
      }


      [XmlAttribute]
      public string roleName
      {
         get { return roleNameField; }
         set { roleNameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class ResourceNameToUnregisterList
   {
      private EndpointReference[] resourceNameField;


      [XmlElement("ResourceName")]
      public EndpointReference[] ResourceName
      {
         get { return resourceNameField; }
         set { resourceNameField = value; }
      }
   }


   [GeneratedCode("xsd", "2.0.50727.1432")]
   [Serializable]

   [DesignerCategory("code")]
   [XmlType(AnonymousType = true, Namespace = "http://jsr262.dev.java.net/jmxconnector")]
   [XmlRoot(Namespace = "http://jsr262.dev.java.net/jmxconnector", IsNullable = false)]
   public partial class RelationChange
   {
      private string idField;
      private object itemField;
      private EndpointReference relationNameField;

      private string typeField;


      public EndpointReference RelationName
      {
         get { return relationNameField; }
         set { relationNameField = value; }
      }


      [XmlElement("ResourceNameToUnregisterList", typeof(ResourceNameToUnregisterList))]
      [XmlElement("RoleUpdate", typeof(RoleUpdate))]
      public object Item
      {
         get { return itemField; }
         set { itemField = value; }
      }


      [XmlAttribute]
      public string id
      {
         get { return idField; }
         set { idField = value; }
      }


      [XmlAttribute]
      public string type
      {
         get { return typeField; }
         set { typeField = value; }
      }
   }
}