//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMX.WebUI.WebControls.Resources
{
	using System;
	using System.Globalization;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class AttributeTableRow
	{

		private static global::System.Resources.ResourceManager resourceMan;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal AttributeTableRow()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMX.WebUI.WebControls.Resources.AttributeTableRow", typeof(AttributeTableRow).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		private static CultureInfo CurrentCulture
		{
			get { return CultureInfo.CurrentCulture; }
		}

		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		internal static string CancelButton
		{
			get
			{
				return ResourceManager.GetString("CancelButton", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Edit.
		/// </summary>
		internal static string EditButton
		{
			get
			{
				return ResourceManager.GetString("EditButton", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to R.
		/// </summary>
		internal static string ReadableSymbol
		{
			get
			{
				return ResourceManager.GetString("ReadableSymbol", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to (unreadable).
		/// </summary>
		internal static string UnreadableValue
		{
			get
			{
				return ResourceManager.GetString("UnreadableValue", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		internal static string UpdateButton
		{
			get
			{
				return ResourceManager.GetString("UpdateButton", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to W.
		/// </summary>
		internal static string WritableSymbol
		{
			get
			{
				return ResourceManager.GetString("WritableSymbol", CurrentCulture);
			}
		}
	}
}
