//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMX.WebUI.WebControls.Resources
{
	using System;
	using System.Globalization;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class MBeanUI
	{

		private static global::System.Resources.ResourceManager resourceMan;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal MBeanUI()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMX.WebUI.WebControls.Resources.MBeanUI", typeof(MBeanUI).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		private static CultureInfo CurrentCulture
		{
			get { return CultureInfo.CurrentCulture; }
		}

		/// <summary>
		///   Looks up a localized string similar to Access.
		/// </summary>
		internal static string AttributesAccess
		{
			get
			{
				return ResourceManager.GetString("AttributesAccess", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actions.
		/// </summary>
		internal static string AttributesActions
		{
			get
			{
				return ResourceManager.GetString("AttributesActions", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		internal static string AttributesDescription
		{
			get
			{
				return ResourceManager.GetString("AttributesDescription", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		internal static string AttributesName
		{
			get
			{
				return ResourceManager.GetString("AttributesName", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Attributes.
		/// </summary>
		internal static string AttributesSection
		{
			get
			{
				return ResourceManager.GetString("AttributesSection", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Value.
		/// </summary>
		internal static string AttributesValue
		{
			get
			{
				return ResourceManager.GetString("AttributesValue", CurrentCulture);
			}
		}

      /// <summary>
      ///   Looks up a localized string similar to Access.
      /// </summary>
      internal static string RelationsAccess
      {
         get
         {
            return ResourceManager.GetString("RelationsAccess", CurrentCulture);
         }
      }
     
      /// <summary>
      ///   Looks up a localized string similar to Description.
      /// </summary>
      internal static string RelationsDescription
      {
         get
         {
            return ResourceManager.GetString("RelationsDescription", CurrentCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Name.
      /// </summary>
      internal static string RelationsName
      {
         get
         {
            return ResourceManager.GetString("RelationsName", CurrentCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Attributes.
      /// </summary>
      internal static string RelationsSection
      {
         get
         {
            return ResourceManager.GetString("RelationsSection", CurrentCulture);
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Value.
      /// </summary>
      internal static string RelationsValue
      {
         get
         {
            return ResourceManager.GetString("RelationsValue", CurrentCulture);
         }
      }

		/// <summary>
		///   Looks up a localized string similar to Class.
		/// </summary>
		internal static string GeneralInformationClass
		{
			get
			{
				return ResourceManager.GetString("GeneralInformationClass", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		internal static string GeneralInformationDescription
		{
			get
			{
				return ResourceManager.GetString("GeneralInformationDescription", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Object name.
		/// </summary>
		internal static string GeneralInformationObjectName
		{
			get
			{
				return ResourceManager.GetString("GeneralInformationObjectName", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to General information.
		/// </summary>
		internal static string GeneralInformationSection
		{
			get
			{
				return ResourceManager.GetString("GeneralInformationSection", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actions.
		/// </summary>
		internal static string OperationsActions
		{
			get
			{
				return ResourceManager.GetString("OperationsActions", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Arguments.
		/// </summary>
		internal static string OperationsArguments
		{
			get
			{
				return ResourceManager.GetString("OperationsArguments", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Description.
		/// </summary>
		internal static string OperationsDescription
		{
			get
			{
				return ResourceManager.GetString("OperationsDescription", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Impact.
		/// </summary>
		internal static string OperationsImpact
		{
			get
			{
				return ResourceManager.GetString("OperationsImpact", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		internal static string OperationsName
		{
			get
			{
				return ResourceManager.GetString("OperationsName", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Operations.
		/// </summary>
		internal static string OperationsSection
		{
			get
			{
				return ResourceManager.GetString("OperationsSection", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Refresh.
		/// </summary>
		internal static string RefreshButton
		{
			get
			{
				return ResourceManager.GetString("RefreshButton", CurrentCulture);
			}
		}
	}
}
