//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMX.WebUI.WebControls.Resources
{
	using System;
	using System.Globalization;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class OperationTableRow
	{

		private static global::System.Resources.ResourceManager resourceMan;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal OperationTableRow()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMX.WebUI.WebControls.Resources.OperationTableRow", typeof(OperationTableRow).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		private static CultureInfo CurrentCulture
		{
			get { return CultureInfo.CurrentCulture; }
		}		

		/// <summary>
		///   Looks up a localized string similar to Invoke.
		/// </summary>
		internal static string InvokeButton
		{
			get
			{
				return ResourceManager.GetString("InvokeButton", CurrentCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		internal static string CancelButton
		{
			get
			{
				return ResourceManager.GetString("CancelButton", CurrentCulture);
			}
		}

      /// <summary>
      ///   Looks up a localized string similar to Invocation results.
      /// </summary>
      internal static string ResultsText
      {
         get
         {
            return ResourceManager.GetString("ResultsText", CurrentCulture);
         }
      }
	}
}
