//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MBeanServerDelegate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MBeanServerDelegate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetMX.Resources.MBeanServerDelegate", typeof(MBeanServerDelegate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the this product.
        /// </summary>
        internal static string ImplementationName {
            get {
                return ResourceManager.GetString("ImplementationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer of this product.
        /// </summary>
        internal static string ImplementationVendor {
            get {
                return ResourceManager.GetString("ImplementationVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of this product.
        /// </summary>
        internal static string ImplementationVersion {
            get {
                return ResourceManager.GetString("ImplementationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBean which provides information about agent.
        /// </summary>
        internal static string MBeanServerDelegateMBean {
            get {
                return ResourceManager.GetString("MBeanServerDelegateMBean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent identity.
        /// </summary>
        internal static string MBeanServerId {
            get {
                return ResourceManager.GetString("MBeanServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name of implemented NetMX specification.
        /// </summary>
        internal static string SpecificationName {
            get {
                return ResourceManager.GetString("SpecificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator of implemented NetMX specification.
        /// </summary>
        internal static string SpecificationVendor {
            get {
                return ResourceManager.GetString("SpecificationVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of implemented NetMX specification.
        /// </summary>
        internal static string SpecificationVersion {
            get {
                return ResourceManager.GetString("SpecificationVersion", resourceCulture);
            }
        }
    }
}
